[[bitshuffle]]
arch = "aarch64"
git-tree-sha1 = "c5391d70be2c5de859d608e0cf2e2fd9b32a5328"
os = "macos"

    [[bitshuffle.download]]
    sha256 = "0b33bccae1c10966580edab9287c81851595783933e9e829e91a4edeb8dc50b3"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.aarch64-apple-darwin.tar.gz"
[[bitshuffle]]
arch = "aarch64"
git-tree-sha1 = "a2ee099bd71d7d898ef488fac86057d1cf981ea9"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "513018110695294dd7866f7cee941fd0934faa8725cc6fe3f47ae09a457be3ec"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.aarch64-linux-gnu.tar.gz"
[[bitshuffle]]
arch = "aarch64"
git-tree-sha1 = "580b5f58a3b825a7a7b34ac5ad39faca97c93d88"
libc = "musl"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "5ef7d4d56c55cbaa3bdd00e69f4215d4e09557ae51b661e8e4a35f66386e5800"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.aarch64-linux-musl.tar.gz"
[[bitshuffle]]
arch = "aarch64"
git-tree-sha1 = "d72ce19801e0112bc6412a1f33d9afc22277747c"
os = "freebsd"

    [[bitshuffle.download]]
    sha256 = "d5c8739c1589351887e22d4ff6db1bacf1af8135c414ce6b6e3b911d1a1a848c"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.aarch64-unknown-freebsd.tar.gz"
[[bitshuffle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ed089f25ac4bd3be3414043a3c13675adf5cce6"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "c43051dd4fb942ce698540c64e8d3a1d01de1df17e3d82f95bc8e54137d5aca4"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.armv6l-linux-gnueabihf.tar.gz"
[[bitshuffle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d368232b77ba3998ae31745a4c4920cbac1188b7"
libc = "musl"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "c13c1dd0ec3251be13b1563a3be95ced2b11d6e0060693d4965f4f4e81e88374"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.armv6l-linux-musleabihf.tar.gz"
[[bitshuffle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ed1d143c6c98a0a9a4d1d7a743e7c05f97d9b6b"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "fdf44a210f3ff6f6b79513faac56903c18f0eff27cdf12a1cd6502f5f7d68336"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.armv7l-linux-gnueabihf.tar.gz"
[[bitshuffle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81b834282c8510db26e86f184b31b62aec25b721"
libc = "musl"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "e40c4d13b45ea7ef42ffe637e912e0cd23965f89338d4f1d54eb517af9d6d7ee"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.armv7l-linux-musleabihf.tar.gz"
[[bitshuffle]]
arch = "i686"
git-tree-sha1 = "790f4949594881b545053f75586a9d0855e05b44"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "12cfc924ed08979eccb677c3752c2261055c8cedb2270381f3f3f9beae45bd49"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.i686-linux-gnu.tar.gz"
[[bitshuffle]]
arch = "i686"
git-tree-sha1 = "361c7bb2ef4f48c60108af1d4b34e9153637f75b"
libc = "musl"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "f13a454cd74d9dcc2da6f87fc5dffdf10d02a3e70861dd1ea5ed455d07dde8f9"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.i686-linux-musl.tar.gz"
[[bitshuffle]]
arch = "i686"
git-tree-sha1 = "b92cecf0b9450bf2705253c379b801228f9b1f07"
os = "windows"

    [[bitshuffle.download]]
    sha256 = "270b26a6c9e032c2474d77fe30cbea826157689e03cb3f92b3b0557484e6ab50"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.i686-w64-mingw32.tar.gz"
[[bitshuffle]]
arch = "powerpc64le"
git-tree-sha1 = "13bff50167b36c4a8cac6c34cccf23632f5b93bc"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "d4c286f116cf4c901f243d879ddefb8dd0f90b4598172a1d77bbe707920064da"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.powerpc64le-linux-gnu.tar.gz"
[[bitshuffle]]
arch = "riscv64"
git-tree-sha1 = "9a79a05e9616d3645b1045e713431660e1aa8502"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "d90e4b4bab8bea7e20a2adc8d246b53fe8ce2ba24327483b573817a3ec381d01"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.riscv64-linux-gnu.tar.gz"
[[bitshuffle]]
arch = "x86_64"
git-tree-sha1 = "0a460b35359c3238fc20e161a65431ca0b95e43a"
os = "macos"

    [[bitshuffle.download]]
    sha256 = "1a753129a9d343bebf8364c0cbf76cedced1497cda11472791c2339f2fa78a39"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.x86_64-apple-darwin.tar.gz"
[[bitshuffle]]
arch = "x86_64"
git-tree-sha1 = "ac2d2cc2fb3a50b766ff0357650eaba4048adcd2"
libc = "glibc"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "e4b926333ee387e813e8413211b564a91cd45653026b4ac438e2d6890ae03554"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.x86_64-linux-gnu.tar.gz"
[[bitshuffle]]
arch = "x86_64"
git-tree-sha1 = "e8132542a2bc63351fc37e61b6901769d9ccff45"
libc = "musl"
os = "linux"

    [[bitshuffle.download]]
    sha256 = "32ac396ed451233d82b2e12ac3bd90f7b6eb6d2b8f0334919b6d8fdcc564be99"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.x86_64-linux-musl.tar.gz"
[[bitshuffle]]
arch = "x86_64"
git-tree-sha1 = "948a33cf1d21665291a417c61297db7dae535eeb"
os = "freebsd"

    [[bitshuffle.download]]
    sha256 = "785e552c44db9bda000accdcff1f54b2112a054d6bbe2eb4cc7171b76c1ffa61"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.x86_64-unknown-freebsd.tar.gz"
[[bitshuffle]]
arch = "x86_64"
git-tree-sha1 = "1694c287fae6ea87791a3d8d8d3ef0d6ae26b980"
os = "windows"

    [[bitshuffle.download]]
    sha256 = "419dffdf0f538600dfc381d34b47854ef87cd6aed3663d36f14b6a1df1f44e9e"
    url = "https://github.com/JuliaBinaryWrappers/bitshuffle_jll.jl/releases/download/bitshuffle-v0.5.2+0/bitshuffle.v0.5.2.x86_64-w64-mingw32.tar.gz"
