# Autogenerated wrapper script for bitshuffle_jll for aarch64-apple-darwin
export libbitshuffle

using Lz4_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("bitshuffle")
JLLWrappers.@declare_library_product(libbitshuffle, "@rpath/libbitshuffle.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Lz4_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libbitshuffle,
        "lib/libbitshuffle.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
