# Autogenerated wrapper script for bitshuffle_jll for x86_64-w64-mingw32
export libbitshuffle

using Lz4_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("bitshuffle")
JLLWrappers.@declare_library_product(libbitshuffle, "libbitshuffle.dll")
function __init__()
    JLLWrappers.@generate_init_header(Lz4_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libbitshuffle,
        "bin\\libbitshuffle.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
